### ISSUE TITLE
Please push a JDK 11.0.8 version to DockerHub

### ISSUE THREAD

**Issue by ericwb** [mozilla/docker-sbt#16]
I would like to use this sbt container to build on Java 11.  From the documentation it status a new tag can be pushed to DockerHub by modifying OPENJDK_TAG=11.0.8, but only if a member of the mozilla org.  Can someone please do this? 

Thanks!

**Comment by jklukas** [comment]
Built and pushed: https://hub.docker.com/layers/mozilla/sbt/11.0.8_1.3.13/images/sha256-4559d5f0f43a6bb4a815748db576f90c09203db4c9204d2560d8cbf94d51374f?context=repo
