### ISSUE TITLE
Build SBT tag using Amazon Corretto as JDK

### ISSUE THREAD

**Issue by felipebonezi** [mozilla/docker-sbt#18]
Hey guys, we're using Amazon Corretto JDK version on our services running in AWS.
How do you think to create a tag using this image?

https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

**Comment by jklukas** [comment]
This repository exists primarily to provide an SBT base for Mozilla projects, and most of our use cases for sbt are inactive, as we've moved most of our ETL logic from Spark to BigQuery queries. I don't expect to have much thought put into this repository other than periodically bumping versions.

I'd encourage to look at https://github.com/hseeberger/scala-sbt which is more actively maintained or consider making your own fork.
