### ISSUE TITLE
manifest for mozilla/sbt:latest not found

### ISSUE THREAD

**Issue by ikrauchanka** [mozilla/docker-sbt#2]
$ docker pull mozilla/sbt
Using default tag: latest
Error response from daemon: manifest for mozilla/sbt:latest not found

mac, Version 18.06.0-ce-mac70 (26399)

**Comment by jklukas** [comment]
Thanks for reporting! I pushed a new build with latest versions, and also tagged it as latest. #3 adds pushing of latest tag to publishing instructions.
