### ISSUE TITLE
Network usage

### ISSUE THREAD

**Issue by Fi1osof** [mozilla/docker-sbt#20]
Why image used network permanently?
![Screenshot from 2021-04-23 07-50-38](https://user-images.githubusercontent.com/2550668/115830240-afc49b00-a418-11eb-8355-e99e5f2ddfcf.png)

Stop using and again - restart container.
Started sbt project from disk (not in docker) not using network (working as expected).

**Comment by jklukas** [comment]
Can you check running the base image `openjdk:8u232` and see if you see the same pattern? This Dockerfile here does nothing other than install sbt on top of that image.

**Comment by Fi1osof** [comment]
@jklukas it's can be my mistake. Probably graphql-voyager used schema auto-pull every 3 sec and this lot of traffic. i close this issue.
Sorry for disturb;
