### ISSUE TITLE
bintray is forbidden

### ISSUE THREAD

**Issue by itayB** [mozilla/docker-sbt#22]
seems like jfrog shut down bintray, [this](https://github.com/mozilla/docker-sbt/blob/main/Dockerfile#L13) is not working :(

**Comment by jklukas** [comment]
Looks like they have their own Artifactory instance now: https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1

So we can likely just change the URL to https://repo.scala-sbt.org/scalasbt/debian ; I'm checking on this now.
